#!/bin/bash
# My first script

if [ "$#" -gt 1 ]; then
    echo "Too many arguments";
    exit;
fi

if [ "$1" = "pull" ]; then
    git pull origin master;
    echo "pulled origin";
    exit;
elif [ "$1" = "dev" ]; then
	node index.js;
elif [ "$1" = "start" ]; then
	forever start --uid "production" index.js;
elif [ "$1" = "stop" ]; then
	forever stop production;
else
    echo "========] Git Sh File [========";
    echo "Commands: ";
    echo " - pull";
    echo " - dev";
    echo " - start";
    echo " - stop";
fi



